IMPORTATION DE DONNEES

In [1]:
import pandas as pd

from ydata_profiling import ProfileReport
pd.set_option('display.max_columns',None)

In [2]:
train_data = pd.read_csv('../data/train.csv')
test_data = pd.read_csv('../data/test.csv')
#profile1 = ProfileReport(train_data,title = "Rapport de profilage")
#profile2 = ProfileReport(train_data,title = "Rapport de profilage")
#profile1.to_file('EDA/rapport_train.html')
#profile2.to_file('EDA/rapport_test.html')

In [3]:
train_data

,id,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,0,Male,0,Yes,Yes,29,Yes,No,DSL,Yes,No,Yes,Yes,No,No,One year,Yes,Mailed check,60.10,1653.85,No
1,1,Male,0,Yes,Yes,58,Yes,No,DSL,Yes,Yes,No,Yes,Yes,No,Two year,No,Credit card (automatic),69.50,3778.20,No
2,2,Male,0,Yes,No,58,Yes,Yes,Fiber optic,No,Yes,No,No,Yes,Yes,Month-to-month,Yes,Electronic check,100.40,5841.35,No
3,3,Female,0,No,No,1,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,69.70,70.70,Yes
4,4,Female,0,No,No,1,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.45,70.45,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594189,594189,Male,0,No,No,57,Yes,Yes,Fiber optic,No,No,Yes,No,Yes,Yes,Two year,No,Bank transfer (automatic),97.55,5460.70,No
594190,594190,Female,0,No,No,72,Yes,Yes,DSL,Yes,Yes,Yes,Yes,Yes,Yes,Two year,No,Bank transfer (automatic),91.95,6782.15,No
594191,594191,Female,0,Yes,No,72,Yes,Yes,No,No internet service,No internet service,No internet service,No internet service,No internet service,No internet service,Two year,No,Credit card (automatic),24.40,1871.90,No
594192,594192,Female,0,No,No,32,Yes,Yes,Fiber optic,No,No,No,No,No,Yes,Month-to-month,Yes,Electronic check,86.00,2847.20,No
594193,594193,Female,1,Yes,No,2,Yes,No,DSL,No,No,No,No,Yes,No,Month-to-month,Yes,Electronic check,54.55,108.05,Yes

In [4]:
train_data.describe()

,id,SeniorCitizen,tenure,MonthlyCharges,TotalCharges
count,594194.000000,594194.000000,594194.000000,594194.000000,594194.000000
mean,297096.500000,0.114102,36.577258,65.866223,2494.377057
std,171529.177263,0.317936,25.061922,31.067444,2353.916710
min,0.000000,0.000000,1.000000,18.250000,18.800000
25%,148548.250000,0.000000,12.000000,29.900000,639.650000
50%,297096.500000,0.000000,35.000000,74.100000,1433.650000
75%,445644.750000,0.000000,62.000000,90.800000,4263.800000
max,594193.000000,1.000000,72.000000,118.750000,8684.800000

In [5]:
train_data = train_data.drop('id',axis = 1)

PRETRAITEMENT DE DONNEES

In [6]:
from sklearn.preprocessing import LabelEncoder,StandardScaler
import numpy as np
le = LabelEncoder()
scaler = StandardScaler()
def encoder(df):
     df['gender'] = df['gender'].map({'Male':0,'Female':1})
     df['Partner'] = df['Partner'].map({'No':0, 'Yes':1})
     df['Dependents'] = df['Dependents'].map({'No':0, 'Yes':1})
     df['PhoneService'] = df['PhoneService'].map({'No':0, 'Yes':1})
     df['PaperlessBilling'] = df['PaperlessBilling'].map({'No':0, 'Yes':1})
     df['MultipleLines'] = df['MultipleLines'].replace('No phone service', 'No')
     df['OnlineSecurity'] = df['OnlineSecurity'].replace('No internet service', 'No')
     df['OnlineBackup'] = df['OnlineBackup'].replace('No internet service', 'No')
     df['DeviceProtection'] = df['DeviceProtection'].replace('No internet service', 'No')
     df['TechSupport'] = df['TechSupport'].replace('No internet service', 'No')
     df['StreamingTV'] = df['StreamingTV'].replace('No internet service', 'No')
     df['StreamingMovies'] = df['StreamingMovies'].replace('No internet service', 'No')
     df['MultipleLines'] = df['MultipleLines'].map({'No':0, 'Yes':1})
     df['OnlineSecurity'] = df['OnlineSecurity'].map({'No':0, 'Yes':1})
     df['OnlineBackup'] = df['OnlineBackup'].map({'No':0, 'Yes':1})
     df['DeviceProtection'] = df['DeviceProtection'].map({'No':0, 'Yes':1})
     df['TechSupport'] = df['TechSupport'].map({'No':0, 'Yes':1})
     df['StreamingTV'] = df['StreamingTV'].map({'No':0, 'Yes':1})
     df['StreamingMovies'] = df['StreamingMovies'].map({'No':0, 'Yes':1})
     df['InternetService'] = df['InternetService'].map({'No':0, 'DSL':1, 'Fiber optic':2})
     df['Contract'] = df['Contract'].map({'Month-to-month':0, 'One year':1, 'Two year':2})
     df['PaymentMethod'] = df['PaymentMethod'].map({'Mailed check':0,
                                                'Electronic check':1,
                                                'Bank transfer (automatic)':2,
                                                'Credit card (automatic)':3})
     df['TotalCharges'] = pd.to_numeric(df['TotalCharges'], errors='coerce')
     train_data['Churn'] = train_data['Churn'].map({'No':0,'Yes':1})
     train_data['MonthlyCharges'] = np.log(train_data['MonthlyCharges'])
     train_data['tenure'] = np.log(train_data['tenure'])
     return df

train_data_encoder = encoder(train_data)
def feature_engg(df):
    df['ChargesPerDay'] = (df['MonthlyCharges']/30).round(3)
    df['ChargesPerHours'] = (df['ChargesPerDay']/24).round(3)
    df['SeniorCitizensWithPartner'] = ((df['SeniorCitizen']== 1) & (df['Partner'] == 1)).astype('int')
    return df
train_data_engg = feature_engg(train_data_encoder)

In [7]:
train_data_engg

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn,ChargesPerDay,ChargesPerHours,SeniorCitizensWithPartner
0,0,0,1,1,3.367296,1,0,1,1,0,1,1,0,0,1,1,0,4.096010,1653.85,0,0.137,0.006,0
1,0,0,1,1,4.060443,1,0,1,1,1,0,1,1,0,2,0,3,4.241327,3778.20,0,0.141,0.006,0
2,0,0,1,0,4.060443,1,1,2,0,1,0,0,1,1,0,1,1,4.609162,5841.35,0,0.154,0.006,0
3,1,0,0,0,0.000000,1,0,2,0,0,0,0,0,0,0,1,1,4.244200,70.70,1,0.141,0.006,0
4,1,0,0,0,0.000000,1,0,2,0,0,0,0,0,0,0,1,1,4.254903,70.45,1,0.142,0.006,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
594189,0,0,0,0,4.043051,1,1,2,0,0,1,0,1,1,2,0,2,4.580365,5460.70,0,0.153,0.006,0
594190,1,0,0,0,4.276666,1,1,1,1,1,1,1,1,1,2,0,2,4.521245,6782.15,0,0.151,0.006,0
594191,1,0,1,0,4.276666,1,1,0,0,0,0,0,0,0,2,0,3,3.194583,1871.90,0,0.106,0.004,0
594192,1,0,0,0,3.465736,1,1,2,0,0,0,0,0,1,0,1,1,4.454347,2847.20,0,0.148,0.006,0
594193,1,1,1,0,0.693147,1,0,1,0,0,0,0,1,0,0,1,1,3.999118,108.05,1,0.133,0.006,1

RAPPORT DU PRETRAITEMENT DE DONNEES

In [8]:
#profile3 = ProfileReport(train_data_engg,title = "Rapport de profilage")
#profile3.to_file('EDA/rapport_Trainset_pretraitement.html')

ENTRAINEMENT DU MODEL

In [9]:
from sklearn.model_selection import train_test_split
x = train_data_engg.drop(['Churn'],axis = 1)
y = train_data_engg['Churn']
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.20,stratify=y,random_state=42)

In [10]:
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
rfc = RandomForestClassifier(
                             n_estimators=100,
                             min_samples_split=3,
                             max_depth=20,
                             min_samples_leaf = 1,
                             criterion = 'entropy', 
                             max_features = 'log2',
                             class_weight= 'balanced'
                             )
xgb = XGBClassifier(
                    n_estimators = 200,
                    max_depth = 8,
                    learning_rate = 0.1
)
LGBM = LGBMClassifier(
                    max_depth=3, n_estimators=200, learning_rate=0.05,
                    device='gpu', random_state=42, verbose=-1
    )
LGBM.fit(x_train,y_train)
xgb.fit(x_train,y_train)
rfc.fit(x_train,y_train)
y_proba_lgbm = LGBM.predict_proba(x_test)[:,1]
y_proba_xgb = xgb.predict_proba(x_test)[:,1]
y_proba_rfc = rfc.predict_proba(x_test)[:,1]

In [11]:
from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

stack = StackingClassifier(
    estimators=[
        ('rfc',rfc),
        ('xgb',xgb),
        ('lgbm',LGBM)
    ],
    final_estimator=LogisticRegression()
)
stack.fit(x_train,y_train)
y_proba_stack = stack.predict_proba(x_test)[:,1]

TUNNING DES HYPERPARAMETRES

In [ ]:
from sklearn.model_selection import RandomizedSearchCV

params = {
   'n_estimators':[100,200],
   'max_depth':[6,8],
   'learning_rate':[0.01,0.1],

}
rand = RandomizedSearchCV(xgb,
                          param_distributions=params,
                          n_iter=4,
                          cv = 3,
                          n_jobs=1,
                          scoring = 'roc_auc')
rand.fit(x_train,y_train)
print('best paramètre',rand.best_params_)
print('best score',rand.best_score_)

EVALUATION

In [12]:
from sklearn.metrics import roc_auc_score

print('roc_auc_rfc',roc_auc_score(y_test,y_proba_rfc))
print('roc_auc_lgbm',roc_auc_score(y_test,y_proba_lgbm))
print('roc_auc_xgb',roc_auc_score(y_test,y_proba_xgb))
print('roc_auc_stacking',roc_auc_score(y_test,y_proba_stack))

roc_auc_rfc 0.9092287334829722
roc_auc_lgbm 0.9133368242656092
roc_auc_xgb 0.9160101124863026
roc_auc_stacking 0.9152887703191118

In [ ]:
from sklearn.model_selection import cross_val_score

scores_rfc = cross_val_score(rfc,x,y,cv=5,scoring='roc_auc')
scores_xgb = cross_val_score(xgb,x,y,cv=5,scoring='roc_auc')
print('rfc :',np.mean(scores_rfc))
print('xgb :',np.mean(scores_xgb))

VISUALISATION DU COURBE D'APPRENTISSAGE

In [ ]:
import matplotlib.pyplot as plt
import numpy as np
from xgboost import XGBClassifier
from lightgbm import LGBMClassifier
from sklearn.model_selection import LearningCurveDisplay, ShuffleSplit

fig, ax = plt.subplots(1,3,figsize = (15,5))
models = {
    'XGBoost' : XGBClassifier(
        n_estimators = 200,
        max_depth = 8,
        learning_rate = 0.1
    ),
    'LightGBM' :LGBMClassifier(
        max_depth=100,
        learning_rate=0.1
    ),
    'RandomForest':RandomForestClassifier(
        n_estimators=100,
        min_samples_split=3,
        max_depth=10,
        min_samples_leaf = 1,
        criterion = 'entropy', 
        max_features = 'log2',
        class_weight= 'balanced'
    )
}
cv = ShuffleSplit(n_splits=5,test_size=0.2,random_state=0)

for i,(name,model) in enumerate(models.items()):
    LearningCurveDisplay.from_estimator(model,
                                        x,
                                        y,
                                        cv=cv,
                                        train_sizes=np.linspace(0.1,1.0,5))
    ax[i].set_title(name)
plt.show()

TEST_SET

In [ ]:
test_data1 = test_data.drop(['id'],axis =1)
test_data1

In [ ]:
test_data_encoder = encoder(test_data1)
test_data_engg = feature_engg(test_data_encoder)

In [ ]:
test_data_engg

In [ ]:
y_test_proba = xgb.predict_proba(test_data_engg)[:,1]
y_test_proba

In [ ]:
submission = pd.DataFrame({
    'id' : test_data['id'],
    'Churn' : y_test_proba
    }
)

In [ ]:
submission['Churn'].value_counts()
submission.to_csv('Submission.csv',index=False)